### ISSUE TITLE
Infografía hilos en C#

### ISSUE THREAD

**Issue by KarlaV0** [SistemasTecTlaxiaco/infografia-de-hilos-KarlaV0#2]
[TAP_U3_Infografia_Hilos en C#.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-hilos-KarlaV0/files/6461306/TAP_U3_Infografia_Hilos.en.C.pdf)

**Comment by carlos-chrs** [comment]
20
muy bien echo.

**Comment by josealfredo79** [comment]
Bien hecho y revisado
